// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"time"
)

type Action struct {
	ID          []byte
	ProtocolID  sql.NullString
	Drug        string
	Dosage      sql.NullString
	Time        sql.NullString
	Duration    sql.NullString
	Description sql.NullString
}

type Protocol struct {
	ID          []byte
	Diagnosis   string
	Name        string
	Description string
}

type User struct {
	ID        []byte
	Name      string
	Role      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
